######################## default configuration ####################
baseURL = ""
languageCode = "en-us"
title = "ASD IL SOGNO"
theme = "restaurant-hugo"
summaryLength = "7"
paginate = 6

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
URL = "css/bootstrap.min.css"
[[params.plugins.css]]
URL = "css/slick.css"
[[params.plugins.css]]
URL = "css/font-awesome.min.css"
[[params.plugins.css]]
URL = "css/animate.min.css"
[[params.plugins.css]]
URL = "css/venobox.css"
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/responsive.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/jquery.min.js"
[[params.plugins.js]]
URL = "js/bootstrap.min.js"
[[params.plugins.js]]
URL = "js/slick.min.js"
[[params.plugins.js]]
URL = "js/wow.min.js"
[[params.plugins.js]]
URL = "js/venobox.min.js"
[[params.plugins.js]]
URL = "js/main.js"

############################## navigation ###############################

[[menu.main]]
name = "Home"
URL = "hero-area"
weight = 1

[[menu.main]]
name = "Chi siamo"
URL = "about-us"
weight = 2

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[menu.main]]
name = "Offerta corsi"
URL = "price"
weight = 4

# [[menu.main]]
# name = "News"
# URL = "subscribe"
# weight = 5

[[menu.main]]
name = "Contattaci"
URL = "contact-us"
weight = 6


#################### default parameters ################################
[params]
logo = "images/logo.jpg"
# meta data
author = "Luca Pasut"
description = "This is meta description"
# google analitycs ID
google_analitycs_id = "Your ID"
# copyright
copyright = "Copyright 2020 - All Rights Reserved."

# Preloader
[params.preloader]
enable = false
preloader = "" # use .png , .svg or .gif format

################################### Footer ############################
[params.footer]
enable = true
contactInfoTitle = "CONTAT<span>TI</span>"
blogTitle = "LE ULTIME <span>NEWS</span>"
galleryTitle = "PHOTO <span>STREAM</span>"
socialTitle = "SEGUI<span>CI</span>"

############################ footer contact item
[[params.footer.contactItem]]
title="Telefono"
icon = "fa fa-phone"
content = "3493703954"

[[params.footer.contactItem]]
title="Indirizzo"
icon = "fa fa-map-marker"
content = "Via Peruzza 7, 33170, Pordenone (PN)"

[[params.footer.contactItem]]
title="E mail"
icon = "fa fa-envelope"
content = "associazioneilsogno@gmail.com"

######################### footer gallery
[[params.footer.gallery]]
image = "images/slider/slider-img-1.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-2.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-3.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-4.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-5.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-6.jpg"

######################## Social Icon 
[[params.footer.socialLink]]
icon = "facebook"
link = "https://www.facebook.com/asdilsogno"

[[params.footer.socialLink]]
icon = "instagram"
link = "https://www.instagram.com/asdilsogno"