baseURL = "https://ilsogno.netlify.app"
languageCode = "en-us"
paginate = 6
summaryLength = "7"
theme = "restaurant-hugo"
title = "ASD IL SOGNO"
[[menu.main]]
URL = "hero-area"
name = "Home"
weight = 1
[[menu.main]]
URL = "about-us"
name = "Chi siamo"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "price"
name = "Offerta corsi"
weight = 4
[[menu.main]]
URL = "contact-us"
name = "Contattaci"
weight = 6
[params]
author = "Luca Pasut"
copyright = "Copyright &copy; {year}"
description = "This is meta description"
google_analitycs_id = "Your ID"
logo = "images/logo.jpg"
theme_color = "#ff0ab5"
number_post = 4
[params.footer]
blogTitle = "LE ULTIME <span>NEWS</span>"
contactInfoTitle = "CONTAT<span>TI</span>"
enable = true
galleryTitle = "PHOTO <span>STREAM</span>"
socialTitle = "SEGUI<span>CI</span>"
[[params.footer.contactItem]]
content = "3493703954"
icon = "fa fa-phone"
title = "Telefono"
[[params.footer.contactItem]]
content = "Via Peruzza 7, 33170, Pordenone (PN)"
icon = "fa fa-map-marker"
title = "Indirizzo"
[[params.footer.contactItem]]
content = "associazioneilsogno@gmail.com"
icon = "fa fa-envelope"
title = "E mail"
[[params.footer.gallery]]
image = "images/slider/slider-img-1.jpg"
[[params.footer.gallery]]
image = "images/slider/slider-img-2.jpg"
[[params.footer.gallery]]
image = "images/slider/slider-img-3.jpg"
[[params.footer.gallery]]
image = "images/slider/slider-img-4.jpg"
[[params.footer.gallery]]
image = "images/slider/slider-img-5.jpg"
[[params.footer.gallery]]
image = "images/slider/slider-img-6.jpg"
[[params.footer.socialLink]]
icon = "facebook"
link = "https://www.facebook.com/asdilsogno"
[[params.footer.socialLink]]
icon = "instagram"
link = "https://www.instagram.com/asdilsogno"
[[params.plugins.css]]
URL = "css/bootstrap.min.css"
[[params.plugins.css]]
URL = "css/slick.css"
[[params.plugins.css]]
URL = "css/font-awesome.min.css"
[[params.plugins.css]]
URL = "css/animate.min.css"
[[params.plugins.css]]
URL = "css/venobox.css"
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/responsive.css"
[[params.plugins.js]]
URL = "js/jquery.min.js"
[[params.plugins.js]]
URL = "js/bootstrap.min.js"
[[params.plugins.js]]
URL = "js/slick.min.js"
[[params.plugins.js]]
URL = "js/wow.min.js"
[[params.plugins.js]]
URL = "js/venobox.min.js"
[[params.plugins.js]]
URL = "js/main.js"
[params.preloader]
enable = false
preloader = ""
